name: 'Bump Versions'
description: 'A GitHub Action to easily bump version files'
author: 'Tommaso De Rossi'
branding:
  icon: 'chevrons-up'
  color: 'red'
inputs: 
  version_file:
    description: 'Version file to bump path'
    default: 'VERSION'
    required: false
  prefix:
    description: 'how to prefix the tag'
    default: ''
    required: false
  github_token:
    description: 'the github token to push changes'
    required: false
  branch:
    description: 'The branch to bump version in'
    required: false
    default: ''
outputs:
  version:
    description: New version
  prefix:
    description: Prefix if set
runs:
  using: 'node12'
  main: 'lib/main.js'

# [bump]
# 2.0.32
