name: "Tag commits on develop"

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Apply a tag to the new commit
      uses: mcpierce/github-commit-timestamp-tagger@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        base_version: "v0.0.0"
