name: "Tag commits on develop"

on:
  push:
    branches:
      - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Bump version
              uses: ./
              with:
                  version_file: VERSION
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
