name: "Tag commits on develop"

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Bump versions
      uses: remorses/bump-version@js
      with:
        version_file: ./VERSION
        prefix: dir2 # this will prefix the created tag
        github_token: ${{ secrets.GITHUB_TOKEN }}

